### ISSUE TITLE
Where to post issues with/for odrviewer.io?

### ISSUE THREAD

**Issue by johschmitz** [pageldev/libOpenDRIVE#78]
Since you removed the code for odrviewer.io from this repository where are we supposed to submit issues for it? Is there a secondary repository that you could make public?

I just wanted to post a feature request regarding centering of the view and setting the pivot point using a double click on an element in the scene.

**Comment by grepthat** [comment]
It's a good point. Most issues to odrviewer.io get posted here even though this project is now only the library part. I created the repo odrviewer now which can be used to post and track issues.
https://github.com/grepthat/odrviewer/tree/public
