### ISSUE TITLE
issue when i try to execute emmake make when i am trying to run the web assembly

### ISSUE THREAD

**Issue by RajiSweethaa** [pageldev/libOpenDRIVE#97]
in the project we dont have makefiles and hence when i try to execute emmake make command prompt is showing the error like 
C:\Users\rsenthi2\Documents\new\libOpenDRIVE\build>emmake make
make: make
make: *** No targets specified and no makefile found.  Stop.
emmake: error: 'make' failed (returned 2)
what should i do to solve the error

**Comment by pageldev** [comment]
You probably have to run `emcmake cmake ..`first.
